apiVersion: v1
kind: Service
metadata:
  name: xyfin-service
spec:
  selector:
    app: xyfin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-service
    - protocol: TCP
      port: 90
      targetPort: 9090
      name: grpc-service
  type: LoadBalancer