// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service_xyfin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Xyfin_CreateUser_FullMethodName = "/pb.Xyfin/CreateUser"
)

// XyfinClient is the client API for Xyfin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XyfinClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type xyfinClient struct {
	cc grpc.ClientConnInterface
}

func NewXyfinClient(cc grpc.ClientConnInterface) XyfinClient {
	return &xyfinClient{cc}
}

func (c *xyfinClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Xyfin_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XyfinServer is the server API for Xyfin service.
// All implementations must embed UnimplementedXyfinServer
// for forward compatibility.
type XyfinServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedXyfinServer()
}

// UnimplementedXyfinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXyfinServer struct{}

func (UnimplementedXyfinServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedXyfinServer) mustEmbedUnimplementedXyfinServer() {}
func (UnimplementedXyfinServer) testEmbeddedByValue()               {}

// UnsafeXyfinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XyfinServer will
// result in compilation errors.
type UnsafeXyfinServer interface {
	mustEmbedUnimplementedXyfinServer()
}

func RegisterXyfinServer(s grpc.ServiceRegistrar, srv XyfinServer) {
	// If the following call pancis, it indicates UnimplementedXyfinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Xyfin_ServiceDesc, srv)
}

func _Xyfin_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XyfinServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Xyfin_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XyfinServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Xyfin_ServiceDesc is the grpc.ServiceDesc for Xyfin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Xyfin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Xyfin",
	HandlerType: (*XyfinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Xyfin_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_xyfin.proto",
}
